### ISSUE TITLE
Code reformatting adds white spaces in special construction

### ISSUE THREAD

**Issue by semisedlak** [JanTvrdik/intellij-latte#14]
With special construction ({if} condition with inner html inside span tag) code reformat (CDM+ALT+L) adds white spaces around "{else}" statement:

```
<span>
	{if true}
		<em>TRUE</em>
	{else}
		<em>FALSE</em>
	{/if}
</span>
```

This issue occured on PhpStorm 8, 9 and 10.

**Comment by matej21** [comment]
Not sure I understand, but I think, it is fixed in 0.2

**Comment by semisedlak** [comment]
Hey @matej21, many thanks for new plugin version! But for me this bug was not fixed.
Try this steps:
1. Make new blank latte file
2. Copy & paste my short code snippet from https://github.com/JanTvrdik/intellij-latte/issues/14#issue-132632357
3. Hit "Code -> Reformat Code" from PhpStorm main menu (on OSX it is on ALT+CMD+L key shortcut)

When I do code reformat on code from step 2. (https://github.com/JanTvrdik/intellij-latte/issues/14#issue-132632357)
```
<span>
	{if true}
		<em>TRUE</em>
			
				{else}
		
		<em>FALSE</em>
	{/if}
</span>
```
Do you see how "{else}" moves?

**Comment by matej21** [comment]
I am not able to reproduce it. which phpstorm version are you using? are you sure *.latte files are associated with a latte plugin (Settings/Editor/File types)?

**Comment by hrach** [comment]
For me reformatting of latte doesn't work at all. It formats only the html tags.

**Comment by matej21** [comment]
Could you please check Block structure using this Psi viewer https://www.jetbrains.com/phpstorm/help/viewing-psi-structure.html ?

It should look like this:
![block structure](https://ctrlv.cz/shots/2016/03/12/0088.png)

**Comment by hrach** [comment]
I don't know how to show the block structure. I can show you jsut the psi structure.

**Comment by matej21** [comment]
It is integrated psi viewer in idea/phpstorm, but you need to enable it. See the article from my previous comment.

**Comment by hrach** [comment]
![psi](https://cloud.githubusercontent.com/assets/284263/13725214/37f0a71a-e89b-11e5-9cd0-0b55318bfd19.JPG)

**Comment by matej21** [comment]
But it is indented ok, isn't it? (content under if/else is intended). Or what did you mean by "reformatting of latte"?

**Comment by semisedlak** [comment]
<img width="860" alt="screen shot 2016-03-12 at 21 52 53" src="https://cloud.githubusercontent.com/assets/1753633/13725265/0383bf6a-e89d-11e5-8d5e-c05978f62c0f.png">

**Comment by matej21** [comment]
@semisedlak you are using smarty, not latte.

**Comment by hrach** [comment]
```
<span>
	{if true}<em>TRUE</em>
	{else}
	<em>FALSE</em>
	{/if}
</span>
```
do nothing
-----------

```
`<span>
	{if true}
	<em>TRUE</em>
	{else}
	<em>FALSE</em>
	{/if}
</span>
```
do 
```
<span>
	{if true}
		<em>TRUE</em>
	{else}
	<em>FALSE</em>
	{/if}
</span>
```

**Comment by matej21** [comment]
@hrach it is caused by enabled option Editor/Code style/Html/Other/Keep white spaces. But I will try to fix it anyway

**Comment by hrach** [comment]
I have this option disabled.

**Comment by matej21** [comment]
@hrach oh, I was using stable PhpStorm 10.0. Now I switched to the newest EAP and it is really broken. Not sure if it is a bug or the behaviour was changed intentionally.

**Comment by hrach** [comment]
I'm using stable too :D

**Comment by semisedlak** [comment]
@matej21 yes, it was my bad. I had _****.latte***_ extension registered for Smarty (Preferences -> Editor -> File Types). Now my status is exactly the same as @hrach has written.

**Comment by matej21** [comment]
Oh, it is also affected by "Keep white spacces inside". If you remove "span" it should work. Not sure if I can bypass this..
